src/Entity/Proprietaire.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProprietaireRepository")
 */
class Proprietaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_pharmacie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Garde", inversedBy="proprietaires")
     */
    private $gardes;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Admin", mappedBy="proprietaires")
     */
    private $admins;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="proprietaire", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Produit::class, mappedBy="proprietaire", orphanRemoval=true, cascade={"remove"})
     */
    private $produits;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^(0[5|6|7])[0-9]{8}$/")
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $region;

    public function __construct()
    {
        $this->gardes = new ArrayCollection();
        $this->admins = new ArrayCollection();
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPharmacie(): ?string
    {
        return $this->nom_pharmacie;
    }

    public function setNomPharmacie(string $nom_pharmacie): self
    {
        $this->nom_pharmacie = $nom_pharmacie;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * @return Collection|Garde[]
     */
    public function getGardes(): Collection
    {
        return $this->gardes;
    }

    public function addGarde(Garde $garde): self
    {
        if (!$this->gardes->contains($garde)) {
            $this->gardes[] = $garde;
        }

        return $this;
    }

    public function removeGarde(Garde $garde): self
    {
        if ($this->gardes->contains($garde)) {
            $this->gardes->removeElement($garde);
        }

        return $this;
    }

    /**
     * @return Collection|Admin[]
     */
    public function getAdmins(): Collection
    {
        return $this->admins;
    }

    public function addAdmin(Admin $admin): self
    {
        if (!$this->admins->contains($admin)) {
            $this->admins[] = $admin;
            $admin->addProprietaire($this);
        }

        return $this;
    }

    public function removeAdmin(Admin $admin): self
    {
        if ($this->admins->contains($admin)) {
            $this->admins->removeElement($admin);
            $admin->removeProprietaire($this);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setProprietaire($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->contains($produit)) {
            $this->produits->removeElement($produit);
            // set the owning side to null (unless already changed)
            if ($produit->getProprietaire() === $this) {
                $produit->setProprietaire(null);
            }
        }

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(string $region): self
    {
        $this->region = $region;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(
 *  fields= {"email"},
 *  message= "L'email que vous avez indiqué est déjà utilisé !"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\Length(min="8", minMessage="Votre mot de passe doit faire minimum 8 caractères")
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password", message="Vous n'avez pas le meme mot de passe")
     */
    public $confirm_password;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $prenom;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Client", mappedBy="user", cascade={"persist", "remove"})
     */
    private $client;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Proprietaire", mappedBy="user", cascade={"persist", "remove"})
     */
    private $proprietaire;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Admin", mappedBy="user", cascade={"persist", "remove"})
     */
    private $admin;

    /**
     * @ORM\Column(type="datetime")
     */
    private $RegistredAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\OneToMany(targetEntity=Reclamation::class, mappedBy="user", cascade={"remove"})
     */
    private $reclamation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $statut;

    public function __construct()
    {
        $this->reclamation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(Client $client): self
    {
        $this->client = $client;

        // set the owning side of the relation if necessary
        if ($client->getUser() !== $this) {
            $client->setUser($this);
        }

        return $this;
    }

    public function getProprietaire(): ?Proprietaire
    {
        return $this->proprietaire;
    }

    public function setProprietaire(Proprietaire $proprietaire): self
    {
        $this->proprietaire = $proprietaire;

        // set the owning side of the relation if necessary
        if ($proprietaire->getUser() !== $this) {
            $proprietaire->setUser($this);
        }

        return $this;
    }

    public function getAdmin(): ?Admin
    {
        return $this->admin;
    }

    public function setAdmin(Admin $admin): self
    {
        $this->admin = $admin;

        // set the owning side of the relation if necessary
        if ($admin->getUser() !== $this) {
            $admin->setUser($this);
        }

        return $this;
    }

    public function getRegistredAt(): ?\DateTimeInterface
    {
        return $this->RegistredAt;
    }

    public function setRegistredAt(\DateTimeInterface $RegistredAt): self
    {
        $this->RegistredAt = $RegistredAt;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * @return Collection|reclamation[]
     */
    public function getReclamation(): Collection
    {
        return $this->reclamation;
    }

    public function addReclamation(reclamation $reclamation): self
    {
        if (!$this->reclamation->contains($reclamation)) {
            $this->reclamation[] = $reclamation;
            $reclamation->setUser($this);
        }

        return $this;
    }

    public function removeReclamation(reclamation $reclamation): self
    {
        if ($this->reclamation->contains($reclamation)) {
            $this->reclamation->removeElement($reclamation);
            // set the owning side to null (unless already changed)
            if ($reclamation->getUser() === $this) {
                $reclamation->setUser(null);
            }
        }

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }
    
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('adresse')
            ->add('ville', ChoiceType::class, [
                'choices'  => [
                    'Casablanca' => 'Casablanca',
                    'Fès' => 'Fès',
                    'Salé' => 'Salé',
                    'Tanger' => 'Tanger',
                    'Marrakech' => 'Marrakech',
                    'Meknès' => 'Meknès',
                    'Rabat' => 'Rabat',
                    'Oujda' => 'Oujda',
                    'Kénitra' => 'Kénitra',
                    'Agadir' => 'Agadir',
                    'Tétouan' => 'Tétouan',
                    'Témara' => 'Témara',
                    'Safi' => 'Safi',
                    'Mohammédia' => 'Mohammédia',
                    'Khouribga' => 'Khouribga',
                    'El Jadida' => 'El Jadida',
                    'Béni Mellal' => 'Béni Mellal',
                    'Nador' => 'Nador',
                    'Taza' => 'Taza',
                    'Khémisset' => 'Khémisset',
                    'Autre...' => 'Autre',
                ],
            ])
            ->add('region', ChoiceType::class, [
                'choices'  => [
                    'Tanger-Tétouan-Al Hoceïma' => 'Tanger-Tétouan-Al Hoceïma',
                    'Oriental' => 'Oriental',
                    'Fès-Meknès' => 'Fès-Meknès',
                    'Rabat-Salé-Kénitra' => 'Rabat-Salé-Kénitra',
                    'Béni Mellal-Khénifra' => 'Béni Mellal-Khénifra',
                    'Casablanca-Settat' => 'Casablanca-Settat',
                    'Marrakech-Safi' => 'Marrakech-Safi',
                    'Drâa-Tafilalet' => 'Drâa-Tafilalet',
                    'Souss-Massa' => 'Souss-Massa',
                    'Guelmim-Oued Noun' => 'Guelmim-Oued Noun',
                    'Laâyoune-Sakia El Hamra' => 'Laâyoune-Sakia El Hamra',
                    'Dakhla-Oued Ed-Dahab' => 'Dakhla-Oued Ed-Dahab',
                ],
            ])
            ->add('tel')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

templates/client/CheckoutForm.html.twig
{{ form_start(form, {'attr': {'id': 'checkout_form','action':path('HandleCheckout'),'style':'display:none' }}) }}
    {{ form_widget(form) }}
{{ form_end(form)  }}

templates/client/Compte.html.twig
{% extends 'client/base.html.twig' %}
{% block body %}
<div class="site-section">
      <div class="container">
        <ul class="nav nav-tabs">
            <li class="nav-item">
              <a class="nav-link {{ active_tab1 }}" data-toggle="tab" href="#info">Information Personnelles</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {{ active_tab2 }}" data-toggle="tab" href="#pwd">Changer le mot de passe</a>
            </li>
        
          </ul>
          <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade {{ active_tab1 }}" id="info">
            {% if active_tab1 == "active show" %}
              {% for message in app.flashes('success') %}
                  <div class="alert alert-success" role="success">
                      {{ message }}
                      </div>
              {% endfor %}
            {% endif %}  
          
              {{ form_start(formInfoPerso) }}

              {{ form_row(formInfoPerso.nom, {'label' : 'Nom', 'attr' : {'value' : app.user.nom}}) }}
              {{ form_row(formInfoPerso.prenom, {'label' : 'Prenom', 'attr' : {'value' : app.user.prenom}}) }}    
              {{ form_row(formInfoPerso.adresse, {'label' : 'adresse', 'attr' : {'value' : app.user.client.adresse}}) }}
              {{ form_row(formInfoPerso.ville, {'label':'ville'} ) }}
              {{ form_row(formInfoPerso.region, {'label':'region'} ) }}
              {{ form_row(formInfoPerso.telephone, {'label':'telephone','attr':{'value':app.user.client.Tel}} ) }}
             

              <input type="hidden" name="active_tab" value="tab_1"/>
              {{ form_end(formInfoPerso) }}
            </div>
            <div class="tab-pane fade {{ active_tab2 }}" id="pwd">
            {% if active_tab2 == "active show" %}
              {% for message in app.flashes('success') %}
                  <div class="alert alert-success" role="success">
                      {{ message }}
                      </div>
              {% endfor %}
            {% endif %}  
              
              {{ form_start(formPassword) }}
              
              {{ form_row(formPassword.oldpassword, {'label' : 'Le mot de passe actuel', 'attr' : {'placeholder' : "Ecrire l'ancien mot de passe"}}) }}
              
              <input type="hidden" name="active_tab" value="tab_2"/>
              {{ form_end(formPassword) }}
            </div>

          </div>
            
      </div>
    </div>
    <script>
      document.getElementById('client_change_info_perso_ville').value='{{app.user.client.ville}}';
      document.getElementById('client_change_info_perso_region').value='{{app.user.client.region}}';
    
    </script>
{% endblock %}

templates/client/detailspharmacie.html.twig
{% extends 'client/index.html.twig' %}

{% block body %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<style>
.emp-profile{
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background: #F0F2F1;
}
.profile-img{
    text-align: center;
}
.profile-img img{
    width: 70%;
    height: 100%;
}
.profile-img .file {
    position: relative;
    overflow: hidden;
    margin-top: -20%;
    width: 70%;
    border: none;
    border-radius: 0;
    font-size: 15px;
    background: #212529b8;
}
.profile-img .file input {
    position: absolute;
    opacity: 0;
    right: 0;
    top: 0;
}
.profile-head h5{
    color: #333;
}
.profile-head h6{
    color: #0062cc;
}
.profile-edit-btn{
    border: none;
    border-radius: 1.5rem;
    width: 70%;
    padding: 2%;
    font-weight: 600;
    color: #6c757d;
    cursor: pointer;
}
.proile-rating{
    font-size: 12px;
    color: #818182;
    margin-top: 5%;
}
.proile-rating span{
    color: #495057;
    font-size: 15px;
    font-weight: 600;
}
.profile-head .nav-tabs{
    margin-bottom:5%;
}
.profile-head .nav-tabs .nav-link{
    font-weight:600;
    border: none;
}
.profile-head .nav-tabs .nav-link.active{
    border: none;
    border-bottom:2px solid #0062cc;
}
.profile-work{
    padding: 14%;
    margin-top: -15%;
}
.profile-work p{
    font-size: 12px;
    color: #818182;
    font-weight: 600;
    margin-top: 10%;
}
.profile-work a{
    text-decoration: none;
    color: #495057;
    font-weight: 600;
    font-size: 14px;
}
.profile-work ul{
    list-style: none;
}
.profile-tab label{
    font-weight: 600;
}
.profile-tab p{
    font-weight: 600;
    color: #0062cc;
}
</style>
<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                            <img src="{{asset('images/logo-pharma.png')}}" alt=""/>
                            
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                         ParaPharmacie {{proprietaire.nomPharmacie}}
                                    </h5>
                                    <h6>
                                        PROPRIETAIRE : {{proprietaire.user.nom}} {{proprietaire.user.prenom}}
                                    </h6>
                                    <p class="proile-rating"><span>Inscrit le : </span>{{proprietaire.user.registredAt|date("d/m/Y")}} </p>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">A propos</a>
                                </li>
                            </ul>
                        </div>
                    </div>
               
                </div>
                <div class="row">
                    <div class="col-md-4">
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Email</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{proprietaire.user.email}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Telephone</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{proprietaire.tel}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Adresse</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{proprietaire.adresse}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Ville</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{proprietaire.Ville}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Region</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{proprietaire.region}}</p>
                                            </div>
                                        </div>
                            </div>
                           
                        </div>
                    </div>
                </div>
            </form>           
        </div>
        {% if produits %}
       <center> <h3> Les produits qui correspond a cette Parapharmacie </h3></center>
      <div class="container">
         <div class="row">
            {% for produits in page %}
              <div class="col-lg-3 col-md-6 mt-3">
                <div class="card">
                  <div class="card-body text-center item mb-4" id="p-{{produits.id}}" >
                    <img src="{{asset('images/'~produits.image)}}" alt="Image" class="cart-item" style="max-height:150px">
                    <h3 class="text-dark" id="{{produits.id}}">{{produits.nom}}</a></h3>
                    <a href=" {{path('details', {'id':produits.id})}}" class="btn btn-outline-primary btn-sm"> Details </a> 
                    <p class="price" data-price="{{produits.prixtva}}" data-pr="{{produits.proprietaire.id}}" data-max='{{produits.quantite}}' style="font-weight:bold;color:#008CB6">{{produits.prixtva + produits.prixht}} DH ttc</p>
                    <a href="#" class="btn btn-info btn-sm" class='additem' id='b{{produits.id}}'>Ajouter au panier</a>
                  </div>
                </div>
              </div>


         {% endfor %}

         {% else %}
                <center> <h3> Cette Parapharmacie n'a aucun produit  </h3></center>
        {% endif %}
         </div> <br>
         <div class:"navigation">
              {{ knp_pagination_render(page)}}
              </div>
         </div>




<script>
  console.log(idd);
	   /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	   /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//   console.log(JSON.parse(localStorage.getItem("my_cart_infos")).filter( x=>x.id==idd).map(y=>y.items)[0].reduce(function(acc,v){return {qt:acc.qt+v.qt}}).qt);
  var addtoCart=function(){
  let storage=localStorage.getItem("my_cart_infos");
   //let parent=this.parentElement.getAttribute("id");
   console.log(this.getAttribute('id').replace('b','p-'))
   //return
   let data=document.getElementById(this.getAttribute('id').replace('b','p-'));
   let prodName;
   let prodId;
   let prodPrice;
   let prodImage;
   let prodProp;
   let stck;
   let incr=1;
    for (let i = 0; i < data.children.length; i++) {
    switch (data.children[i].tagName)
	{
	  case 'H3':
	  prodName=data.children[i].innerHTML;
	  prodId=data.children[i].id;
	  break;
	  case 'IMG':
	  prodImage= data.children[i].src;
	  break;
	  case 'P':
	  prodPrice= data.children[i].dataset.price;
    prodProp=data.children[i].dataset.pr;
    stck=data.children[i].dataset.max;
    console.log(data.children[i].dataset)
	  break;
	
	}
	}
   let storage_data={prod_name:prodName,prop:prodProp,price:prodPrice,image:prodImage,id:prodId,qt:1,stock:stck};
   let items_table=(!storage)?[]:JSON.parse(storage);
     console.log(stck);
   if( items_table.map(x=>x.id).indexOf(idd)==-1)
   {  
     
	  items_table.push({id:idd,items:[storage_data]});
   
   }
   else{
     let index=items_table.map(x=>x.id).indexOf(idd);
	 if( items_table[index].items.map(x=>x.id).indexOf(prodId)==-1 )
     items_table[index].items.push(storage_data);
	 else {
     if(items_table[index].items[items_table[index].items.map(x=>x.id).indexOf(prodId)].qt<stck-1)
     
     {items_table[index].items[items_table[index].items.map(x=>x.id).indexOf(prodId)].qt++;incr--;}
   }
 
   }

   localStorage.setItem("my_cart_infos", JSON.stringify(items_table));
   alert(" product  has been added to your cart!!");
   
   //CartProdNumber();//update product numbers in the cart
   let cart=document.getElementById("my-cart");
  // cart.childNodes[3].innerHTML=cart.childNodes[3].innerHTML*1+incr;
  if(storage && JSON.parse(storage).filter( x=>x.id==idd).length )
   {cart.childNodes[3].innerHTML=JSON.parse(storage).filter( x=>x.id==idd).map(y=>y.items)[0].reduce(function(acc,v){return {qt:acc.qt*1 +v.qt*1}}).qt*1 +1}
   else
   {cart.childNodes[3].innerHTML++;}
  
  }
  //Array.from(document.getElementsByClassName("cart-item")).forEach( function(item){   item.addEventListener("click",addtoCart)     }  )
  Array.from(document.getElementsByClassName("btn btn-info btn-sm")).forEach( function(item){   item.addEventListener("click",addtoCart)     }  )
  //////////////// Add an item to the cart ////////////////////////////////////////////////////
  ////////////////////////////////////////////////////////////////////////////////////////////
  
  </script>

{% endblock %}

templates/client/list-pharmacie.html.twig
{% extends 'client/base.html.twig' %}

{% block body %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
.cards{
display: grid;
 
grid-template-columns: repeat(3, 1fr);
 
grid-auto-rows: auto;
 
grid-gap: 1rem;
}
.card {
 
 width:100%;
padding: .5rem;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px;
  margin: auto;
  text-align: center;
  font-family: arial;
}

.title {
  color: grey;
  font-size: 18px;
}

.click {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

.social {
  text-decoration: none;
  font-size: 22px;
  color: black;
}

button:hover, a:hover {
  opacity: 0.7;
}
</style>
<br><br>
<center><h1> Les Parapharmacie </h1></center>
<br>
      {{render(controller('App\\Controller\\ClientController::SearchProp'))}}
<br>
<div class="cards">
{% for pharmacies in page %}
      <div class="card">
  <img src="/w3images/team2.jpg" alt="" style="width:100%">
  <center><h3>Parapharmacie<br> {{pharmacies.nomPharmacie}}</h3></center>
  <center><p class="title">{{pharmacies.adresse}}</p></center>
 <center> <p>{{pharmacies.ville}}</p></center>
 <center> <div style="margin: 24px 0;">
    <a class="social" href="#"><i class="fa fa-dribbble"></i></a> 
    <a class="social" href="#"><i class="fa fa-twitter"></i></a>  
    <a class="social" href="#"><i class="fa fa-linkedin"></i></a>  
    <a class="social" href="#"><i class="fa fa-facebook"></i></a> 
  </div></center>
  <p> <a href="{{ path('profile', {'id':pharmacies.id})}}"> <button class="click">Profile</button></a></p>
</div>
{% endfor %}
  
</div>
<br><br>
<div class:"navigation">
              {{ knp_pagination_render(page)}}
              </div>
{% endblock %}