src/Entity/Produit.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitRepository")
 * @Vich\Uploadable
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     */
    private $date_expiration;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_ht;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_tva;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="image")
     */
    private $imageFile;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="produits")
     * @ORM\JoinColumn(nullable=true)
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DetailsCommande", mappedBy="produit", cascade={"remove"})
     */
    private $commandes;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite;

    /**
     * @ORM\ManyToOne(targetEntity=Proprietaire::class, inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $proprietaire;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateExpiration(): ?\DateTimeInterface
    {
        return $this->date_expiration;
    }

    public function setDateExpiration(?\DateTimeInterface $date_expiration): self
    {
        $this->date_expiration = $date_expiration;

        return $this;
    }

    public function getPrixHt(): ?float
    {
        return $this->prix_ht;
    }

    public function setPrixHt(?float $prix_ht): self
    {
        $this->prix_ht = $prix_ht;

        return $this;
    }

    public function getPrixTva(): ?float
    {
        return $this->prix_tva;
    }

    public function setPrixTva(?float $prix_tva): self
    {
        $this->prix_tva = $prix_tva;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile): Produit
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection|DetailsCommande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(DetailsCommande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setProduit($this);
        }

        return $this;
    }

    public function removeCommande(DetailsCommande $commande): self
    {
        if ($this->commandes->contains($commande)) {
            $this->commandes->removeElement($commande);
            // set the owning side to null (unless already changed)
            if ($commande->getProduit() === $this) {
                $commande->setProduit(null);
            }
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getProprietaire(): ?Proprietaire
    {
        return $this->proprietaire;
    }

    public function setProprietaire(?Proprietaire $proprietaire): self
    {
        $this->proprietaire = $proprietaire;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Entity/Proprietaire.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProprietaireRepository")
 */
class Proprietaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_pharmacie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Garde", inversedBy="proprietaires")
     */
    private $gardes;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Admin", mappedBy="proprietaires")
     */
    private $admins;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="proprietaire", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Produit::class, mappedBy="proprietaire", orphanRemoval=true, cascade={"remove"})
     */
    private $produits;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^(0[5|6|7])[0-9]{8}$/")
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $region;

    public function __construct()
    {
        $this->gardes = new ArrayCollection();
        $this->admins = new ArrayCollection();
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPharmacie(): ?string
    {
        return $this->nom_pharmacie;
    }

    public function setNomPharmacie(string $nom_pharmacie): self
    {
        $this->nom_pharmacie = $nom_pharmacie;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * @return Collection|Garde[]
     */
    public function getGardes(): Collection
    {
        return $this->gardes;
    }

    public function addGarde(Garde $garde): self
    {
        if (!$this->gardes->contains($garde)) {
            $this->gardes[] = $garde;
        }

        return $this;
    }

    public function removeGarde(Garde $garde): self
    {
        if ($this->gardes->contains($garde)) {
            $this->gardes->removeElement($garde);
        }

        return $this;
    }

    /**
     * @return Collection|Admin[]
     */
    public function getAdmins(): Collection
    {
        return $this->admins;
    }

    public function addAdmin(Admin $admin): self
    {
        if (!$this->admins->contains($admin)) {
            $this->admins[] = $admin;
            $admin->addProprietaire($this);
        }

        return $this;
    }

    public function removeAdmin(Admin $admin): self
    {
        if ($this->admins->contains($admin)) {
            $this->admins->removeElement($admin);
            $admin->removeProprietaire($this);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setProprietaire($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->contains($produit)) {
            $this->produits->removeElement($produit);
            // set the owning side to null (unless already changed)
            if ($produit->getProprietaire() === $this) {
                $produit->setProprietaire(null);
            }
        }

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(string $region): self
    {
        $this->region = $region;

        return $this;
    }
}

src/Form/ProprietaireType.php
<?php

namespace App\Form;

use App\Entity\Proprietaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ProprietaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_pharmacie')
            ->add('adresse')
            ->add('ville', ChoiceType::class, [
                'choices'  => [
                    'Casablanca' => 'Casablanca',
                    'Fès' => 'Fès',
                    'Salé' => 'Salé',
                    'Tanger' => 'Tanger',
                    'Marrakech' => 'Marrakech',
                    'Meknès' => 'Meknès',
                    'Rabat' => 'Rabat',
                    'Oujda' => 'Oujda',
                    'Kénitra' => 'Kénitra',
                    'Agadir' => 'Agadir',
                    'Tétouan' => 'Tétouan',
                    'Témara' => 'Témara',
                    'Safi' => 'Safi',
                    'Mohammédia' => 'Mohammédia',
                    'Khouribga' => 'Khouribga',
                    'El Jadida' => 'El Jadida',
                    'Béni Mellal' => 'Béni Mellal',
                    'Nador' => 'Nador',
                    'Taza' => 'Taza',
                    'Khémisset' => 'Khémisset',
                    'Autre...' => 'Autre',
                ],
            ])
            ->add('region', ChoiceType::class, [
                'choices'  => [
                    'Tanger-Tétouan-Al Hoceïma' => 'Tanger-Tétouan-Al Hoceïma',
                    'Oriental' => 'Oriental',
                    'Fès-Meknès' => 'Fès-Meknès',
                    'Rabat-Salé-Kénitra' => 'Rabat-Salé-Kénitra',
                    'Béni Mellal-Khénifra' => 'Béni Mellal-Khénifra',
                    'Casablanca-Settat' => 'Casablanca-Settat',
                    'Marrakech-Safi' => 'Marrakech-Safi',
                    'Drâa-Tafilalet' => 'Drâa-Tafilalet',
                    'Souss-Massa' => 'Souss-Massa',
                    'Guelmim-Oued Noun' => 'Guelmim-Oued Noun',
                    'Laâyoune-Sakia El Hamra' => 'Laâyoune-Sakia El Hamra',
                    'Dakhla-Oued Ed-Dahab' => 'Dakhla-Oued Ed-Dahab',
                ],
            ])
            ->add('tel')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Proprietaire::class,
        ]);
    }
}

templates/proprietaire/_delete_form.html.twig
<form class="d-inline" method="post" action="{{ path('produit_delete', {'id': products.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ products.id) }}">
    <button class="btn btn-danger btn-sm" style="width: 100px">Supprimer</button>
</form>

templates/proprietaire/_form.html.twig
{{ form_start(form) }}
    
    {{ form_row(form.nom,  {'label_attr': {'class': 'text-black'}, 'attr' : {'placeholder' : "Nom du produit"}}) }}
    {{ form_row(form.description, {'label_attr': {'class': 'text-black'}, 'attr' : {'placeholder' : "Description"}}) }}
    {{ form_row(form.date_expiration, {'label_attr': {'class': 'text-black'} }) }}
    {{ form_row(form.prix_ht, {'label_attr': {'class': 'text-black'}, 'attr' : {'placeholder' : "Prix HT"}}) }}
    {{ form_row(form.prix_tva, {'label_attr': {'class': 'text-black'}, 'attr' : {'placeholder' : "Prix TVA"}}) }}
    {{ form_row(form.imageFile, {'label_attr': {'class': 'text-black'}, 'attr' : {'placeholder' : "Image du produit"}}) }}
    {{ form_row(form.categorie, {'label_attr': {'class': 'text-black'}, 'attr' : {'placeholder' : "Categorie"}}) }}
    {{ form_row(form.quantite, {'label_attr': {'class': 'text-black'}, 'attr' : {'placeholder' : "Quantité"}}) }}

    <input type="hidden" name="active_tab" value="tab_2"/>
    
    <button class="btn {{ btn_type|default('btn-primary') }}" style="width: 170px">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/proprietaire/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">
        <link rel="stylesheet" href="{{ asset('fonts/icomoon/style.css') }}">
        <script src="https://use.fontawesome.com/80640ba15b.js"></script>
        <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/magnific-popup.css') }}">
        <link rel="stylesheet" href="{{ asset('css/jquery-ui.css') }}">
        <link rel="stylesheet" href="{{ asset('css/owl.carousel.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/owl.theme.default.min.css') }}">


        <link rel="stylesheet" href="{{ asset('css/aos.css') }}">

        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
        
        {% block stylesheets %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        {% endblock %}
    </head>
    <body>
    <div class="site-wrap">
        {% block header %}
            <div class="site-navbar py-2">

                <div class="search-wrap">
                  <div class="container">
                    <a href="#" class="search-close js-search-close"><span class="icon-close2"></span></a>
                        <form action="#" method="post">
                          <input type="text" class="form-control" placeholder="Search keyword and hit enter...">
                        </form>
                  </div>
                </div>

                <div class="container">
                  <div class="d-flex align-items-center justify-content-between">
                    <div class="logo">
                      <div class="site-logo">
                        <a href="{{ path('home_proprietaire') }}">  <img src="{{asset('images/logosite.png')}}" alt="" style="max-height:50px"/></a>
                      </div>
                    </div>

                    <div class="main-nav d-none d-lg-block">
                      <nav class="site-navigation text-right text-md-center" role="navigation">
                        <ul class="site-menu js-clone-nav d-none d-lg-block">
                          <li class="{{ (app.request.get('_route') == 'stock_proprietaire' or app.request.get('_route') == 'produit_edit' 
                          or app.request.get('_route') == 'produit_show') ? 'active' : '' }}"><a href="{{ path('stock_proprietaire') }}" class="hyper">Stock</a></li>
                          <li class="{{ (app.request.get('_route') == 'commande_proprietaire') ? 'active' : '' }}"><a href="{{ path('commande_proprietaire') }}" class="hyper">Commande</a></li>
                          <li class="{{ (app.request.get('_route') == 'vente_proprietaire') ? 'active' : '' }}"><a href="{{ path('vente_proprietaire') }}" class="hyper">Vente</a></li>
                         {% if app.user %}
                          <li class="{{ (app.request.get('_route') == 'contactprop') ? 'active' : '' }}"><a href="{{path('contactprop')}}" class="hyper">Contact</a></li>
                        {% endif %}
                        </ul>
                      </nav>
                    </div>
                    <div class="site-navigation">
                      
                        <ul class="site-menu">
                          <li><a href="#" class="icons-btn d-inline-block js-search-open"><span class="icon-search"></span></a><li>          
                          <li><a href="#" class="site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none"><span
                              class="icon-menu"></span>
                          </a></li>
        
                          <li class="has-children">
                              <a href="#">{{app.user.proprietaire.nomPharmacie}}</a>
                              <ul class="dropdown">
                                <li>
                                    <a href="{{ path('compte_proprietaire') }}">Paramètres</a>
                                    <a href="{{ path('app_logout') }}">Déconnexion</a>
                                </li>
                              </ul>
                          </li> 
                        </ul>
                         
                    </div>
                  </div>
                </div>
            </div>
            {% block nav %}
            <div class="bg-light py-3">
              <div class="container">
                <div class="row">
                  <div class="col-md-12 mb-0">
                    <a href="{{ path('home_proprietaire') }}">Home</a> <span class="mx-2 mb-0">/</span>
                    <strong class="text-black">{{pagetitle}}</strong>
                  </div>
                </div>
              </div>
            </div>
            {% endblock %}
        {% endblock %}
        {% block body %}{% endblock %}
        {% block footer %}
            <footer class="site-footer">
              <div class="container">
                <div class="row">
                  <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

                    <div class="block-7">
                      <h3 class="footer-heading mb-4">A propos de nous</h3>
                      <p>Le site web ParaClic est fait pour faciliter l'achat des médicament ou les produit médicaux, dont lequel par un seul clic vous pouvez achetez ce que vous voulez </p>
                    </div>

                  </div>
                  <div class="col-lg-3 mx-auto mb-5 mb-lg-0">
                    <h3 class="footer-heading mb-4">Quick Links</h3>
                    <ul class="list-unstyled">
                      <li><a href="#">Supplements</a></li>
                      <li><a href="#">Vitamins</a></li>
                      <li><a href="#">Diet &amp; Nutrition</a></li>
                      <li><a href="#">Tea &amp; Coffee</a></li>
                    </ul>
                  </div>

                  <div class="col-md-6 col-lg-3">
                    <div class="block-5 mb-5">
                      <h3 class="footer-heading mb-4">Contact Info</h3>
                      <ul class="list-unstyled">
                        <li class="address">Lot chabab, Bd ALMAQDIS et rue ALISSRAE N°7 Hay El Qods, Oujda, MAROC</li>
                        <li class="phone"><a>06 94 84 77 10</a></li>
                        <li class="email">paraclic@gmail.com</li>
                      </ul>
                    </div>


                  </div>
                </div>
                <div class="row pt-5 mt-5 text-center">
                  <div class="col-md-12">
                    <p>
                      <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                      Copyright &copy;
                      <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made
                      with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank"
                        class="text-primary">Colorlib</a>
                      <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                  </div>

                </div>
              </div>
            </footer>
        {% endblock %}
    </div>
        {% block javascripts %}
            <script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
            <script src="{{ asset('js/jquery-ui.js') }}"></script>
            <script src="{{ asset('js/popper.min.js') }}"></script>
            <script src="{{ asset('js/bootstrap.min.js') }}"></script>
            <script src="{{ asset('js/owl.carousel.min.js') }}"></script>
            <script src="{{ asset('js/jquery.magnific-popup.min.js') }}"></script>
            <script src="{{ asset('js/aos.js') }}"></script>
            <script src="{{ asset('js/main.js') }}"></script>
        {% endblock %}
    </body>
</html>

templates/proprietaire/compte.html.twig
{% extends 'proprietaire/base.html.twig' %}
{% block title %}Compte {% endblock %}
{% block body %}
<div class="site-section">
      <div class="container">
        <ul class="nav nav-tabs">
            <li class="nav-item">
              <a class="nav-link {{ active_tab1 }}" data-toggle="tab" href="#info">Information Personnelles</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {{ active_tab2 }}" data-toggle="tab" href="#pwd">Changer le mot de passe</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {{ active_tab3 }}" data-toggle="tab" href="#pharmacie">Information de Parapharmacie</a>
              </li>
          </ul>
          <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade {{ active_tab1 }}" id="info">
            {% if active_tab1 == "active show" %}
              {% for message in app.flashes('success') %}
                  <div class="alert alert-success" role="success">
                      {{ message }}
                      </div>
              {% endfor %}
            {% endif %}  
          
              {{ form_start(formInfoPerso) }}

              {{ form_row(formInfoPerso.nom, {'label' : 'Nom', 'attr' : {'value' : app.user.nom}}) }}
              {{ form_row(formInfoPerso.prenom, {'label' : 'Prenom', 'attr' : {'value' : app.user.prenom}}) }}

              <input type="hidden" name="active_tab" value="tab_1"/>
              {{ form_end(formInfoPerso) }}
            </div>
            <div class="tab-pane fade {{ active_tab2 }}" id="pwd">
            {% if active_tab2 == "active show" %}
              {% for message in app.flashes('success') %}
                  <div class="alert alert-success" role="success">
                      {{ message }}
                      </div>
              {% endfor %}
            {% endif %}  
              
              {{ form_start(formPassword) }}
              
              {{ form_row(formPassword.oldpassword, {'label' : 'Le mot de passe actuel', 'attr' : {'placeholder' : "Ecrire l'ancien mot de passe"}}) }}
              
              <input type="hidden" name="active_tab" value="tab_2"/>
              {{ form_end(formPassword) }}
            </div>


            <div class="tab-pane fade {{ active_tab3 }}" id="pharmacie">
            {% if active_tab3 == "active show" %}
              {% for message in app.flashes('success') %}
                  <div class="alert alert-success" role="success">
                      {{ message }}
                      </div>
              {% endfor %}
            {% endif %}  
              
              {{ form_start(formInfoPharma)}}
              {{ form_row(formInfoPharma.nom_pharmacie, {'label' : 'Nom de Parapharmacie', 'attr' : {'value' : app.user.proprietaire.nomPharmacie}}) }}
              {{ form_row(formInfoPharma.adresse_pharmacie, {'label' : 'Adresse', 'attr' : {'value' : app.user.proprietaire.adresse}}) }}
              {{ form_row(formInfoPharma.ville, {'label' : 'Ville', 'attr' : {'value' : app.user.proprietaire.ville}}) }}
              {{ form_row(formInfoPharma.tel, {'label' : 'Tel', 'attr' : {'value' : app.user.proprietaire.tel}}) }}

              <input type="hidden" name="active_tab" value="tab_3"/>
              {{ form_end(formInfoPharma)}}
              

              </div>
          </div>
            
      </div>
    </div>
{% endblock %}

templates/proprietaire/edit.html.twig
{% extends 'proprietaire/base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
<div class="container">
    <h1>Edit Produit</h1>

    
    {{ include('proprietaire/_form.html.twig', {'button_label': 'Modifier', 'btn_type': 'btn-warning'}) }}
    <a href="{{ path('stock_proprietaire') }}" class="btn btn-outline-secondary mt-1" style="width: 170px">Retour à la liste</a>
    
</div>    
{% endblock %}

templates/proprietaire/show.html.twig
{% extends 'proprietaire/base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}

<div class="container">
        <div class="row">
          <div class="col-md-5 mr-auto">
            <div class="border text-center">
              <img src={{ asset('images/' ~ products.image) }} alt="Image" class="img-fluid p-5">
            </div>
          </div>
          <div class="col-md-6">
            <h2 class="text-black">{{ products.nom }}</h2>
            <p>{{ products.description }}</p>
            
            <p>Prix HT :<strong class="text-primary h4">{{ products.prixHt }} dh</strong></p>
            <p>Prix TVA :<strong class="text-primary h4">{{ products.prixTva }} dh</strong></p>
            <p>Date d'expiration :<strong class="text-primary h4">{{ products.dateExpiration ? products.dateExpiration|date('Y-m-d') : '' }}</strong></p>
            <p>Quantité :<strong class="text-primary h4">{{ products.quantite }}</strong></p>
            
            
          </div>
          
        </div>

        
        <a href="{{ path('stock_proprietaire') }}" class="btn btn-outline-secondary btn-sm" style="width: 135px">Retour à la liste</a>

        <a href="{{ path('produit_edit', {'id': products.id}) }}" class="btn btn-warning btn-sm" style="width: 100px">Modifier</a>

        {{ include('proprietaire/_delete_form.html.twig') }}
        
      </div>
{% endblock %}